#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Oct 19, 2017 09:28:40 PM
#    Oct 19, 2017 09:51:34 PM
#    Oct 19, 2017 09:52:35 PM
#    Nov 08, 2017 05:24:34 PM
#    Nov 08, 2017 10:20:35 PM

import sys

try:
    from Tkinter import *
except ImportError:
    # noinspection PyUnresolvedReferences
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

from controlador import Controlador


def desconectar():
    print('pantalla_support.desconectar')
    sys.stdout.flush()
    controlador.desconectar()


def check_ssl():
    print('pantalla_support.check_ssl')
    sys.stdout.flush()
    controlador.accion_seleccion_ssl()


def limpiar_pantalla():
    print('pantalla_support.limpiar_pantalla')
    sys.stdout.flush()
    controlador.limpiar_pantalla()


def cargar_datos():
    print('pantalla_support.cargar_datos')
    sys.stdout.flush()
    controlador.cargar_datos_bd()


def set_Tk_var():
    global che55
    che55 = StringVar()


def conectar():
    print('pantalla_support.conectar')
    controlador.conectar()
    sys.stdout.flush()


def init(top, gui, *args, **kwargs):
    global w, top_level, root, controlador
    w = gui
    top_level = top
    root = top

    controlador = Controlador(gui=w)
    controlador.configurar_gui()


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    import pantalla
    pantalla.vp_start_gui()
