#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m60" -background {#f1f1f1} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 922x493+479+253
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1902 1028
    wm minsize $top 176 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab38 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#f1f1f1} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Servidor Pop:} 
    vTcl:DefineAlias "$top.lab38" "labelServidorPop" vTcl:WidgetProc "Toplevel1" 1
    button $top.but40 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command conectar -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Conectar 
    vTcl:DefineAlias "$top.but40" "conectar_btn" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent41 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black 
    vTcl:DefineAlias "$top.ent41" "servidor_entry" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd45 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#f1f1f1} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Usuario: 
    vTcl:DefineAlias "$top.cpd45" "usuario_lb" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd46 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#f1f1f1} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Puerto(SSL): 
    vTcl:DefineAlias "$top.cpd46" "puerto_lb" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd47 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#f1f1f1} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Contrasenia: 
    vTcl:DefineAlias "$top.cpd47" "contrasenia_lb" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd48 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#f1f1f1} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Frecuencia: 
    vTcl:DefineAlias "$top.cpd48" "frecuencia_lb" vTcl:WidgetProc "Toplevel1" 1
    entry $top.cpd49 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.cpd49" "usuario_entry" vTcl:WidgetProc "Toplevel1" 1
    entry $top.cpd50 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.cpd50" "contrasenia_entry" vTcl:WidgetProc "Toplevel1" 1
    entry $top.cpd51 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.cpd51" "frecuencia_entry" vTcl:WidgetProc "Toplevel1" 1
    entry $top.cpd52 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.cpd52" "puerto_entry" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che55 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#f1f1f1} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text SSL -variable che55 
    vTcl:DefineAlias "$top.che55" "ssl_check" vTcl:WidgetProc "Toplevel1" 1
    button $top.but56 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command desconectar \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Desconectar 
    vTcl:DefineAlias "$top.but56" "desconectar_btn" vTcl:WidgetProc "Toplevel1" 1
    listbox $top.lis57 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -height 256 -width 654 
    .top37.lis57 configure -font TkFixedFont
    .top37.lis57 insert end text
    vTcl:DefineAlias "$top.lis57" "info_listbox" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab58 \
        -anchor w -background {#f1f1f1} -disabledforeground {#a3a3a3} \
        -foreground {#8000ff} -text Desconectado 
    vTcl:DefineAlias "$top.lab58" "estado_conexion_info" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab59 \
        -anchor e -background {#f1f1f1} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Estado conexion:} 
    vTcl:DefineAlias "$top.lab59" "estado_conexion_lb" vTcl:WidgetProc "Toplevel1" 1
    menu $top.m60 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab38 \
        -in $top -x 10 -y 10 -width 135 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but40 \
        -in $top -x 790 -y 10 -width 105 -relwidth 0 -height 70 -relheight 0 \
        -anchor ne -bordermode ignore 
    place $top.ent41 \
        -in $top -x 150 -y 10 -width 174 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.cpd45 \
        -in $top -x 10 -y 50 -width 135 -height 30 -anchor nw \
        -bordermode inside 
    place $top.cpd46 \
        -in $top -x 350 -y 10 -width 135 -height 30 -anchor nw \
        -bordermode inside 
    place $top.cpd47 \
        -in $top -x 10 -y 90 -width 135 -height 30 -anchor nw \
        -bordermode inside 
    place $top.cpd48 \
        -in $top -x 10 -y 130 -width 135 -height 30 -anchor nw \
        -bordermode inside 
    place $top.cpd49 \
        -in $top -x 150 -y 50 -width 174 -height 30 -anchor nw \
        -bordermode inside 
    place $top.cpd50 \
        -in $top -x 150 -y 90 -width 174 -height 30 -anchor nw \
        -bordermode inside 
    place $top.cpd51 \
        -in $top -x 150 -y 130 -width 174 -height 30 -anchor nw \
        -bordermode inside 
    place $top.cpd52 \
        -in $top -x 490 -y 10 -width 174 -height 30 -anchor nw \
        -bordermode inside 
    place $top.che55 \
        -in $top -x 360 -y 60 -anchor nw -bordermode ignore 
    place $top.but56 \
        -in $top -x 910 -y 10 -width 105 -height 70 -anchor ne \
        -bordermode ignore 
    place $top.lis57 \
        -in $top -x 500 -y 480 -width 654 -relwidth 0 -height 256 \
        -relheight 0 -anchor s -bordermode ignore 
    place $top.lab58 \
        -in $top -x 910 -y 110 -width 271 -relwidth 0 -height 31 -relheight 0 \
        -anchor ne -bordermode ignore 
    place $top.lab59 \
        -in $top -x 620 -y 110 -width 177 -relwidth 0 -height 31 -relheight 0 \
        -anchor ne -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

