#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Aug 31, 2017 07:27:26 PM


import sys
from conexion import Conexion

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global combobox
    combobox = StringVar()

def conectar():
    print('principal_support.conectar')

    w.Scrolledlistbox1.delete(0, END)
    w.Scrolledlistbox2.delete(0, END)
    w.Scrolledlistbox3.delete(0, END)

    if (verificar_datos()):
        conectado = conexion.conexion_puerto(puerto=w.puertoEntry.get(), baudrate=w.baudiosEntry.get(),
                                         timeout=w.timeoutEntry.get())
    else:
        conectado = False

    if (conectado):
        w.conectarBtn.config(state=DISABLED)
        w.desconectarBtn.config(state=NORMAL)

        funcion = w.funcionCombo.get()
        w.estadoLabel.config(text='Conectado')
        if(funcion=="3"):
            conexion.ejecutar_funcion03(intentos=w.intentosEntry.get(),
                                        dispositivo=w.dispositivoEntry.get(),
                                        direccion=w.direccionEntry.get(), cantidadRegistros=w.variablesEntry.get())
        if(funcion=="6"):
            conexion.ejecutar_funcion06(intentos=w.intentosEntry.get(),dispositivo=w.dispositivoEntry.get(),
                                        direccion=w.direccionEntry.get(),variable=w.EntryVariable1.get())

        if(funcion=="16"):
            conexion.ejecutar_funcion16(intentos=w.intentosEntry.get(),registros=w.variablesEntry.get(),dispositivo=w.dispositivoEntry.get(),
                                        direccion=w.direccionEntry.get(),variable1=w.EntryVariable1.get(),
                                        variable2=w.EntryVariable2.get(),variable3=w.EntryVariable3.get(),variable4=w.EntryVariable4.get())

    else:
        w.conectarBtn.config(state=NORMAL)
        w.desconectarBtn.config(state=DISABLED)
        w.estadoLabel.config(text='Error al conectar')

    sys.stdout.flush()

def convertirBinario():
    print('principal_support.convertirBinario')
    conexion.imprimirRespuesta(conexion.datosBinario)
    sys.stdout.flush()

def convertirDecimal():
    print('principal_support.convertirDecimal')
    conexion.imprimirRespuesta(conexion.datosDecimal)
    sys.stdout.flush()

def convertirHexadecimal():
    print('principal_support.convertirHexadecimal')
    conexion.imprimirRespuesta(conexion.datosHexadecimal)
    sys.stdout.flush()

def desconectar():
    print('principal_support.desconectar')
    desconectar=conexion.desconectarpuerto()
    if(desconectar):
        w.conectarBtn.config(state=NORMAL)
        w.desconectarBtn.config(state=DISABLED)

        w.Scrolledlistbox1.delete(0,END)
        w.Scrolledlistbox2.delete(0, END)
        w.Scrolledlistbox3.delete(0, END)

        w.estadoLabel.config(text='Desconectado')

        conexion.datosDecimal=[]
        conexion.datosHexadecimal=[]
        conexion.datosBinario=[]
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root, conexion
    w = gui
    top_level = top
    root = top
    conexion = Conexion(gui=w)

    w.conectarBtn.config(state=NORMAL)
    w.desconectarBtn.config(state=DISABLED)

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import principal
    principal.vp_start_gui()


def verificar_datos():

    index = 1
    datos_correctos = True

    if (w.puertoEntry.get()==''):
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Puerto incorrecto")
        index = index + 1

    if w.baudiosEntry.get() == '':
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Baudios incorrectos")
        index = index + 1
    elif not w.baudiosEntry.get().isdigit():
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Baudios incorrectos")
        index = index + 1
    elif not isinstance(int(w.baudiosEntry.get()),(int, long)):
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Baudios incorrectos")
        index = index + 1
    """  
    if w.timeoutEntry.get() == '':
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Timeout incorrecto")
        index = index + 1
    elif not w.timeoutEntry.get().isdigit():
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Timeout incorrecto")
        index = index + 1
    elif not isinstance(int(w.timeoutEntry.get()),(int, long)):
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Timeout incorrecto")
        index = index + 1
    """
    
    if w.intentosEntry.get() == '':
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Cantidad intentos incorrectos")
        index = index + 1
    elif not w.intentosEntry.get().isdigit():
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Cantidad intentos incorrectos")
        index = index + 1
    elif not isinstance(int(w.intentosEntry.get()),(int, long)):
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Cantidad intentos incorrectos")
        index = index + 1

    if w.dispositivoEntry.get() == '':
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Numero dispositivo incorrecto")
        index = index + 1
    elif not w.dispositivoEntry.get().isdigit():
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Numero dispositivo incorrecto")
        index = index + 1
    elif not isinstance(int(w.dispositivoEntry.get()),(int, long)):
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Numero dispositivo incorrecto")
        index = index + 1

    if w.direccionEntry.get() == '':
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Direccion incorrecta")
        index = index + 1
    elif not w.direccionEntry.get().isdigit():
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Direccion incorrecta")
        index = index + 1
    elif not isinstance(int(w.direccionEntry.get()),(int, long)):
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Direccion incorrecta")
        index = index + 1

    cantidad_de_variables = 0
    if w.variablesEntry.get() == '':
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Cantidad variables incorrecta")
        index = index + 1
    elif not w.variablesEntry.get().isdigit():
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Cantidad variables incorrecta")
        index = index + 1
    elif not isinstance(int(w.variablesEntry.get()),(int, long)):
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Cantidad variables incorrecta")
        index = index + 1
    else:
        cantidad_de_variables = int(w.variablesEntry.get())

    if (w.funcionCombo.get() == '' or not (w.funcionCombo.get() == '3' or w.funcionCombo.get() == '6' or w.funcionCombo.get() == '16')):
        datos_correctos = False
        w.Scrolledlistbox1.insert(index, "Funcion incorrecta")
        index = index + 1

    if w.funcionCombo.get() == '6':

        if w.EntryVariable1.get() == '':
            datos_correctos = False
            w.Scrolledlistbox1.insert(index, "Variable incorrecta")
            index = index + 1
        elif not w.EntryVariable1.get().isdigit():
            datos_correctos = False
            w.Scrolledlistbox1.insert(index, "Variable incorrecta")
            index = index + 1
        elif not isinstance(int(w.EntryVariable1.get()),(int, long)):
            datos_correctos = False
            w.Scrolledlistbox1.insert(index, "Variable incorrecta")
            index = index + 1

    if w.funcionCombo.get() == '16':

            if cantidad_de_variables >= 1:
                if w.EntryVariable1.get() == '':
                    datos_correctos = False
                    w.Scrolledlistbox1.insert(index, "Variable 1 incorrecta")
                    index = index + 1
                elif not w.EntryVariable1.get().isdigit():
                    datos_correctos = False
                    w.Scrolledlistbox1.insert(index, "Variable 1 incorrecta")
                    index = index + 1
                elif not isinstance(int(w.EntryVariable1.get()), (int, long)):
                    datos_correctos = False
                    w.Scrolledlistbox1.insert(index, "Variable 1 incorrecta")
                    index = index + 1
                elif int(w.EntryVariable1.get()) > 65535:
                    datos_correctos = False
                    w.Scrolledlistbox1.insert(index, "Variable 1 incorrecta")
                    index = index + 1

            if cantidad_de_variables >= 2:
                if w.EntryVariable2.get() == '':
                    datos_correctos = False
                    w.Scrolledlistbox1.insert(index, "Variable 2 incorrecta")
                    index = index + 1
                elif not w.EntryVariable2.get().isdigit():
                    datos_correctos = False
                    w.Scrolledlistbox1.insert(index, "Variable 2 incorrecta")
                    index = index + 1
                elif not isinstance(int(w.EntryVariable2.get()), (int, long)):
                    datos_correctos = False
                    w.Scrolledlistbox1.insert(index, "Variable 2 incorrecta")
                    index = index + 1
                elif int(w.EntryVariable2.get()) > 65535:
                    datos_correctos = False
                    w.Scrolledlistbox1.insert(index, "Variable 2 incorrecta")
                    index = index + 1

            if cantidad_de_variables >= 3:
                if w.EntryVariable3.get() == '':
                    datos_correctos = False
                    w.Scrolledlistbox1.insert(index, "Variable 3 incorrecta")
                    index = index + 1
                elif not w.EntryVariable3.get().isdigit():
                    datos_correctos = False
                    w.Scrolledlistbox1.insert(index, "Variable 3 incorrecta")
                    index = index + 1
                elif not isinstance(int(w.EntryVariable3.get()), (int, long)):
                    datos_correctos = False
                    w.Scrolledlistbox1.insert(index, "Variable 3 incorrecta")
                    index = index + 1
                elif int(w.EntryVariable3.get()) > 65535:
                    datos_correctos = False
                    w.Scrolledlistbox1.insert(index, "Variable 3 incorrecta")
                    index = index + 1

            if cantidad_de_variables == 4:
                if w.EntryVariable4.get() == '':
                    datos_correctos = False
                    w.Scrolledlistbox1.insert(index, "Variable 4 incorrecta")
                    index = index + 1
                elif not w.EntryVariable4.get().isdigit():
                    datos_correctos = False
                    w.Scrolledlistbox1.insert(index, "Variable 4 incorrecta")
                    index = index + 1
                elif not isinstance(int(w.EntryVariable4.get()), (int, long)):
                    datos_correctos = False
                    w.Scrolledlistbox1.insert(index, "Variable 4 incorrecta")
                    index = index + 1
                elif int(w.EntryVariable4.get()) > 65535:
                    datos_correctos = False
                    w.Scrolledlistbox1.insert(index, "Variable 4 incorrecta")
                    index = index + 1

    return datos_correctos