#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Sep 28, 2017 09:05:09 PM


import sys

from controlador import Controlador

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


# Init
if __name__ == '__main__':
    import principal
    principal.vp_start_gui()


def init(top, gui, *args, **kwargs):
    global w, top_level, root, controlador
    w = gui
    top_level = top
    root = top

    controlador = Controlador(gui=w)
    controlador.configurar_gui()


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def set_Tk_var():
    global combobox
    combobox = StringVar()
    global tch37
    tch37 = StringVar()


# Button Actions

def puertoSerialRBSeleccionado():
    print('principal_support.puertoSerialRBSeleccionado')
    controlador.seleccionar_puerto_serial()
    sys.stdout.flush()


def tcpRBSeleccionado():
    print('principal_support.tcpRBSeleccionado')
    controlador.seleccionar_tcp()
    sys.stdout.flush()


def conectar():
    print('principal_support.conectar')
    controlador.conectar()
    sys.stdout.flush()


def convertirBinario():
    print('principal_support.convertirBinario')
    controlador.convertir_binario()
    sys.stdout.flush()


def convertirDecimal():
    print('principal_support.convertirDecimal')
    controlador.convertir_decimal()
    sys.stdout.flush()


def convertirHexadecimal():
    print('principal_support.convertirHexadecimal')
    controlador.convertir_hexadecimal()
    sys.stdout.flush()


def desconectar():
    print('principal_support.desconectar')
    controlador.desconectar()
    sys.stdout.flush()
