#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Nov 09, 2017 09:53:24 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import pagina_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel_1 (root)
    pagina_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel_1 (w)
    pagina_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("1354x705+-17+2")
        top.title("New Toplevel 1")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.38, rely=0.0, height=31, width=146)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''PROTOCOLO 1''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.04, rely=0.1, height=21, width=112)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''ID EQUIPO:''')

        self.Label3 = Label(top)
        self.Label3.place(relx=0.05, rely=0.17, height=21, width=112)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''CODIGO FUNCION:''')

        self.Label4 = Label(top)
        self.Label4.place(relx=0.05, rely=0.23, height=21, width=112)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''DIRECCION:''')

        self.Label5 = Label(top)
        self.Label5.place(relx=0.05, rely=0.28, height=31, width=122)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''CANTIDAD VARIABLES:''')

        self.idEquipo1 = Entry(top)
        self.idEquipo1.place(relx=0.18, rely=0.1, relheight=0.04, relwidth=0.12)
        self.idEquipo1.configure(background="white")
        self.idEquipo1.configure(disabledforeground="#a3a3a3")
        self.idEquipo1.configure(font="TkFixedFont")
        self.idEquipo1.configure(foreground="#000000")
        self.idEquipo1.configure(highlightbackground="#d9d9d9")
        self.idEquipo1.configure(highlightcolor="black")
        self.idEquipo1.configure(insertbackground="black")
        self.idEquipo1.configure(selectbackground="#c4c4c4")
        self.idEquipo1.configure(selectforeground="black")

        self.idCodigoFuncion1 = Entry(top)
        self.idCodigoFuncion1.place(relx=0.18, rely=0.16, relheight=0.04
                , relwidth=0.12)
        self.idCodigoFuncion1.configure(background="white")
        self.idCodigoFuncion1.configure(disabledforeground="#a3a3a3")
        self.idCodigoFuncion1.configure(font="TkFixedFont")
        self.idCodigoFuncion1.configure(foreground="#000000")
        self.idCodigoFuncion1.configure(highlightbackground="#d9d9d9")
        self.idCodigoFuncion1.configure(highlightcolor="black")
        self.idCodigoFuncion1.configure(insertbackground="black")
        self.idCodigoFuncion1.configure(selectbackground="#c4c4c4")
        self.idCodigoFuncion1.configure(selectforeground="black")

        self.Entry3 = Entry(top)
        self.Entry3.place(relx=0.18, rely=0.22, relheight=0.04, relwidth=0.12)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")

        self.Entry4 = Entry(top)
        self.Entry4.place(relx=0.18, rely=0.28, relheight=0.04, relwidth=0.12)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(highlightbackground="#d9d9d9")
        self.Entry4.configure(highlightcolor="black")
        self.Entry4.configure(insertbackground="black")
        self.Entry4.configure(selectbackground="#c4c4c4")
        self.Entry4.configure(selectforeground="black")

        self.Label6 = Label(top)
        self.Label6.place(relx=0.17, rely=0.04, height=21, width=101)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''CONFIGURACION''')

        self.Entry5 = Entry(top)
        self.Entry5.place(relx=0.37, rely=0.1, relheight=0.2, relwidth=0.58)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(highlightbackground="#d9d9d9")
        self.Entry5.configure(highlightcolor="black")
        self.Entry5.configure(insertbackground="black")
        self.Entry5.configure(selectbackground="#c4c4c4")
        self.Entry5.configure(selectforeground="black")

        self.Label7 = Label(top)
        self.Label7.place(relx=0.64, rely=0.04, height=21, width=45)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''SALIDA''')

        self.Label8 = Label(top)
        self.Label8.place(relx=0.44, rely=0.46, height=21, width=86)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(activeforeground="black")
        self.Label8.configure(background="#d9d9d9")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(highlightbackground="#d9d9d9")
        self.Label8.configure(highlightcolor="black")
        self.Label8.configure(text='''PROTOCOLO 2''')

        self.Label9 = Label(top)
        self.Label9.place(relx=0.18, rely=0.54, height=21, width=101)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(background="#d9d9d9")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(highlightbackground="#d9d9d9")
        self.Label9.configure(highlightcolor="black")
        self.Label9.configure(text='''CONFIGURACION''')

        self.Label10 = Label(top)
        self.Label10.place(relx=0.64, rely=0.53, height=21, width=48)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(activeforeground="black")
        self.Label10.configure(background="#d9d9d9")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(highlightbackground="#d9d9d9")
        self.Label10.configure(highlightcolor="black")
        self.Label10.configure(text='''SALIDA''')

        self.Label11 = Label(top)
        self.Label11.place(relx=0.05, rely=0.62, height=21, width=112)
        self.Label11.configure(activebackground="#f9f9f9")
        self.Label11.configure(activeforeground="black")
        self.Label11.configure(background="#d9d9d9")
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(highlightbackground="#d9d9d9")
        self.Label11.configure(highlightcolor="black")
        self.Label11.configure(text='''ID EQUIPO:''')

        self.Label12 = Label(top)
        self.Label12.place(relx=0.06, rely=0.7, height=21, width=112)
        self.Label12.configure(activebackground="#f9f9f9")
        self.Label12.configure(activeforeground="black")
        self.Label12.configure(background="#d9d9d9")
        self.Label12.configure(disabledforeground="#a3a3a3")
        self.Label12.configure(foreground="#000000")
        self.Label12.configure(highlightbackground="#d9d9d9")
        self.Label12.configure(highlightcolor="black")
        self.Label12.configure(text='''TEMPERATURA:''')

        self.Label13 = Label(top)
        self.Label13.place(relx=0.05, rely=0.77, height=21, width=112)
        self.Label13.configure(activebackground="#f9f9f9")
        self.Label13.configure(activeforeground="black")
        self.Label13.configure(background="#d9d9d9")
        self.Label13.configure(disabledforeground="#a3a3a3")
        self.Label13.configure(foreground="#000000")
        self.Label13.configure(highlightbackground="#d9d9d9")
        self.Label13.configure(highlightcolor="black")
        self.Label13.configure(text='''CORRIENTE:''')

        self.Label14 = Label(top)
        self.Label14.place(relx=0.05, rely=0.85, height=21, width=112)
        self.Label14.configure(activebackground="#f9f9f9")
        self.Label14.configure(activeforeground="black")
        self.Label14.configure(background="#d9d9d9")
        self.Label14.configure(disabledforeground="#a3a3a3")
        self.Label14.configure(foreground="#000000")
        self.Label14.configure(highlightbackground="#d9d9d9")
        self.Label14.configure(highlightcolor="black")
        self.Label14.configure(text='''TENSION:''')

        self.idEquipo2 = Entry(top)
        self.idEquipo2.place(relx=0.18, rely=0.61, relheight=0.04, relwidth=0.12)

        self.idEquipo2.configure(background="white")
        self.idEquipo2.configure(disabledforeground="#a3a3a3")
        self.idEquipo2.configure(font="TkFixedFont")
        self.idEquipo2.configure(foreground="#000000")
        self.idEquipo2.configure(highlightbackground="#d9d9d9")
        self.idEquipo2.configure(highlightcolor="black")
        self.idEquipo2.configure(insertbackground="black")
        self.idEquipo2.configure(selectbackground="#c4c4c4")
        self.idEquipo2.configure(selectforeground="black")

        self.temperatura = Entry(top)
        self.temperatura.place(relx=0.18, rely=0.69, relheight=0.04
                , relwidth=0.12)
        self.temperatura.configure(background="white")
        self.temperatura.configure(disabledforeground="#a3a3a3")
        self.temperatura.configure(font="TkFixedFont")
        self.temperatura.configure(foreground="#000000")
        self.temperatura.configure(highlightbackground="#d9d9d9")
        self.temperatura.configure(highlightcolor="black")
        self.temperatura.configure(insertbackground="black")
        self.temperatura.configure(selectbackground="#c4c4c4")
        self.temperatura.configure(selectforeground="black")

        self.corriente = Entry(top)
        self.corriente.place(relx=0.18, rely=0.76, relheight=0.04, relwidth=0.12)

        self.corriente.configure(background="white")
        self.corriente.configure(disabledforeground="#a3a3a3")
        self.corriente.configure(font="TkFixedFont")
        self.corriente.configure(foreground="#000000")
        self.corriente.configure(highlightbackground="#d9d9d9")
        self.corriente.configure(highlightcolor="black")
        self.corriente.configure(insertbackground="black")
        self.corriente.configure(selectbackground="#c4c4c4")
        self.corriente.configure(selectforeground="black")

        self.tension = Entry(top)
        self.tension.place(relx=0.18, rely=0.83, relheight=0.04, relwidth=0.12)
        self.tension.configure(background="white")
        self.tension.configure(disabledforeground="#a3a3a3")
        self.tension.configure(font="TkFixedFont")
        self.tension.configure(foreground="#000000")
        self.tension.configure(highlightbackground="#d9d9d9")
        self.tension.configure(highlightcolor="black")
        self.tension.configure(insertbackground="black")
        self.tension.configure(selectbackground="#c4c4c4")
        self.tension.configure(selectforeground="black")

        self.tension2 = Entry(top)
        self.tension2.place(relx=0.37, rely=0.63, relheight=0.2, relwidth=0.58)
        self.tension2.configure(background="white")
        self.tension2.configure(disabledforeground="#a3a3a3")
        self.tension2.configure(font="TkFixedFont")
        self.tension2.configure(foreground="#000000")
        self.tension2.configure(highlightbackground="#d9d9d9")
        self.tension2.configure(highlightcolor="black")
        self.tension2.configure(insertbackground="black")
        self.tension2.configure(selectbackground="#c4c4c4")
        self.tension2.configure(selectforeground="black")

        self.conectar1 = Button(top)
        self.conectar1.place(relx=0.07, rely=0.37, height=34, width=117)
        self.conectar1.configure(activebackground="#d9d9d9")
        self.conectar1.configure(activeforeground="#000000")
        self.conectar1.configure(background="#d9d9d9")
        self.conectar1.configure(command=pagina_support.conectar_protocolo_1)
        self.conectar1.configure(disabledforeground="#a3a3a3")
        self.conectar1.configure(foreground="#000000")
        self.conectar1.configure(highlightbackground="#d9d9d9")
        self.conectar1.configure(highlightcolor="black")
        self.conectar1.configure(pady="0")
        self.conectar1.configure(text='''CONECTAR''')

        self.desconectar1 = Button(top)
        self.desconectar1.place(relx=0.18, rely=0.37, height=34, width=137)
        self.desconectar1.configure(activebackground="#d9d9d9")
        self.desconectar1.configure(activeforeground="#000000")
        self.desconectar1.configure(background="#d9d9d9")
        self.desconectar1.configure(command=pagina_support.desconectar_protocolo_1)
        self.desconectar1.configure(disabledforeground="#a3a3a3")
        self.desconectar1.configure(foreground="#000000")
        self.desconectar1.configure(highlightbackground="#d9d9d9")
        self.desconectar1.configure(highlightcolor="black")
        self.desconectar1.configure(pady="0")
        self.desconectar1.configure(text='''DESCONECTAR''')

        self.conectar2 = Button(top)
        self.conectar2.place(relx=0.07, rely=0.91, height=34, width=117)
        self.conectar2.configure(activebackground="#d9d9d9")
        self.conectar2.configure(activeforeground="#000000")
        self.conectar2.configure(background="#d9d9d9")
        self.conectar2.configure(command=pagina_support.conectar_protocolo_2)
        self.conectar2.configure(disabledforeground="#a3a3a3")
        self.conectar2.configure(foreground="#000000")
        self.conectar2.configure(highlightbackground="#d9d9d9")
        self.conectar2.configure(highlightcolor="black")
        self.conectar2.configure(pady="0")
        self.conectar2.configure(text='''CONECTAR''')

        self.desconectar2 = Button(top)
        self.desconectar2.place(relx=0.18, rely=0.91, height=34, width=117)
        self.desconectar2.configure(activebackground="#d9d9d9")
        self.desconectar2.configure(activeforeground="#000000")
        self.desconectar2.configure(background="#d9d9d9")
        self.desconectar2.configure(command=pagina_support.desconectar_protocolo_2)
        self.desconectar2.configure(disabledforeground="#a3a3a3")
        self.desconectar2.configure(foreground="#000000")
        self.desconectar2.configure(highlightbackground="#d9d9d9")
        self.desconectar2.configure(highlightcolor="black")
        self.desconectar2.configure(pady="0")
        self.desconectar2.configure(text='''DESCONECTAR''')






if __name__ == '__main__':
    vp_start_gui()



