#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Aug 30, 2017 06:47:52 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global combobox
    combobox = StringVar()

def conectar():
    print('principal_support.conectar')
    w.puertoEntry.get()
    w.dispositivoEntry.get()
    w.direccionEntry.get()
    w.timeoutEntry.get()
    w.baudiosEntry.get()
    w.variablesEntry.get()
    w.intentosEntry.get()
    sys.stdout.flush()

def convertirBinario():
    print('principal_support.convertirBinario')
    sys.stdout.flush()

def convertirDecimal():
    print('principal_support.convertirDecimal')
    sys.stdout.flush()

def convertirHexadecimal():
    print('principal_support.convertirHexadecimal')
    sys.stdout.flush()

def desconectar():
    print('principal_support.desconectar')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import principal
    principal.vp_start_gui()


